AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*'
    - 'bin/**/*'
  Exclude:
    - 'features/**/*'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 81

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 14

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6
