language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1.10
      jdk: openjdk6
    - rvm: 2.1.10
      jdk: openjdk7
    - rvm: 2.1.10
      jdk: oraclejdk7
    - rvm: 2.2.5
      jdk: openjdk6
    - rvm: 2.2.5
      jdk: openjdk7
    - rvm: 2.2.5
      jdk: oraclejdk7
    - rvm: 2.3.1
      jdk: openjdk6
    - rvm: 2.3.1
      jdk: openjdk7
    - rvm: 2.3.1
      jdk: oraclejdk7
    - rvm: rbx-2
      jdk: openjdk6
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: rbx-2
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
