language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk8
    - rvm: 2.2.0
      jdk: openjdk6
    - rvm: 2.2.0
      jdk: openjdk7
    - rvm: 2.2.0
      jdk: oraclejdk7
    - rvm: 2.2.0
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: oraclejdk8
